ALTER TABLE students ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS first_lesson_date DATE;
ALTER TABLE students ADD COLUMN IF NOT EXISTS card_last_four TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS card_brand TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS total_lessons_taken INTEGER DEFAULT 0;
ALTER TABLE students ADD COLUMN IF NOT EXISTS total_paid NUMERIC DEFAULT 0;
ALTER TABLE families ADD COLUMN IF NOT EXISTS card_last_four TEXT;
ALTER TABLE families ADD COLUMN IF NOT EXISTS card_brand TEXT;
