ALTER TABLE leads ADD COLUMN IF NOT EXISTS age_range TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS experience TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS has_instrument TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS preferred_locations TEXT[];
ALTER TABLE leads ADD COLUMN IF NOT EXISTS personality_notes TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS student_name TEXT;
