import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'content-type, authorization',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

function json(body: Record<string, unknown>, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: corsHeaders })
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    )

    // Parse webhook payload — the new issue row
    const payload = await req.json()
    const record = payload.record ?? payload
    const issueId = record.id

    if (!issueId) return json({ error: 'No issue ID' }, 400)

    // Fetch full issue with reporter profile
    const { data: issue, error: issueErr } = await supabase
      .from('issues')
      .select('*, profiles!reported_by(first_name, last_name, role)')
      .eq('id', issueId)
      .single()

    if (issueErr || !issue) {
      return json({ error: 'Issue not found', detail: issueErr?.message }, 404)
    }

    const reporterName = issue.profiles
      ? `${issue.profiles.first_name ?? ''} ${issue.profiles.last_name ?? ''}`.trim()
      : 'Unknown'

    // Generate screenshot URL if present
    let screenshotUrl = 'None provided'
    if (issue.screenshot_path) {
      const { data: urlData } = await supabase.storage
        .from('issue-screenshots')
        .createSignedUrl(issue.screenshot_path, 3600)
      if (urlData?.signedUrl) screenshotUrl = urlData.signedUrl
    }

    // Build scope restriction block for non-owner reporters
    let scopeRestriction = ''
    if (issue.reported_by_role !== 'owner' && issue.reported_by_role !== 'admin') {
      scopeRestriction = `
━━━ SCOPE RESTRICTION ━━━
This issue was reported by a ${issue.reported_by_role},
not an admin. You may ONLY fix the specific bug,
display issue, or data problem described above.

You may NOT:
- Make structural changes to the app
- Add new features or pages
- Redesign layouts or change the design system
- Modify the database schema
- Change navigation structure
- Alter permissions or role logic

If the fix genuinely requires any of the above,
do NOT proceed. Instead:
1. Update the issues table:
   UPDATE issues SET
     status = 'failed_build',
     resolution_notes = 'Requires structural change — escalated to admin for review.',
     pipeline_completed_at = now(),
     updated_at = now()
   WHERE id = '${issueId}';
2. Stop. Do not write code.
━━━ END SCOPE RESTRICTION ━━━`
    }

    // Generate pipeline prompt
    const prompt = `ISSUE AUTO-FIX — GENERATED BY LP ISSUE REPORTER
Do NOT skip any step. Follow this exactly.

Every time you post a report, ask a question, or need
board approval, you MUST @-mention Zach in the comment.
Without an @-mention it will not appear in the inbox and
Zach will miss it. Always end comments with @Zach.

ISSUE ID: ${issue.id}
SEVERITY: ${issue.severity}
REPORTED BY: ${reporterName} (${issue.reported_by_role})
REPORTED AT: ${issue.created_at}

WHERE IN THE APP:
  Page: ${issue.page}
  Section: ${issue.section}
  Subsection: ${issue.subsection ?? 'N/A'}
  Platform: ${issue.platform ?? 'both'}
  Element: ${issue.element_description}
  Reported from URL: ${issue.reported_from_url ?? 'N/A'}
  Screen size: ${issue.reported_screen_width ?? '?'}x${issue.reported_screen_height ?? '?'}

CATEGORY: ${issue.category}
TITLE: ${issue.title}

DESCRIPTION:
${issue.description}

SCREENSHOT URL: ${screenshotUrl}
${scopeRestriction}

INSTRUCTIONS:
1. Read the issue carefully. Identify which component
   file(s) correspond to Page: ${issue.page}, Section: ${issue.section}${issue.subsection ? `, Subsection: ${issue.subsection}` : ''}.
2. Diagnose the root cause.
3. Implement the minimal fix. Do not refactor unrelated code.
4. Run: npm run build
5. IF BUILD PASSES:
   a. Run: vercel --prod
   b. Update the database:
      UPDATE issues SET
        status = 'resolved',
        deploy_status = 'deployed',
        resolution_notes = '[Describe exactly what you changed and why]',
        resolved_at = now(),
        resolved_by = 'system:claude_code',
        pipeline_completed_at = now(),
        updated_at = now()
      WHERE id = '${issueId}';
   c. Insert notification for the reporter:
      INSERT INTO notifications (
        tenant_id, profile_id, type, title, body,
        reference_type, reference_id
      ) VALUES (
        '${issue.tenant_id}',
        '${issue.reported_by}',
        'issue_resolved',
        'Issue Fixed: ${issue.title.replace(/'/g, "''")}',
        'Your reported issue has been automatically fixed and deployed.',
        'issue',
        '${issueId}'
      );
6. IF BUILD FAILS:
   a. Do NOT deploy. Do NOT run vercel --prod.
   b. Update the database:
      UPDATE issues SET
        status = 'failed_build',
        deploy_status = 'failed',
        resolution_notes = '[Paste the build error output here]',
        pipeline_completed_at = now(),
        updated_at = now()
      WHERE id = '${issueId}';
   c. Insert notification for the admin (owner):
      INSERT INTO notifications (
        tenant_id, profile_id, type, title, body,
        reference_type, reference_id
      ) VALUES (
        '${issue.tenant_id}',
        (SELECT id FROM profiles WHERE tenant_id = '${issue.tenant_id}' AND role = 'owner' LIMIT 1),
        'issue_build_failed',
        'Build Failed: ${issue.title.replace(/'/g, "''")}',
        'Auto-fix pipeline failed for this issue. Manual review needed.',
        'issue',
        '${issueId}'
      );

RULES:
- V9 design system. Do not change design tokens.
- "session" not "lesson" everywhere.
- Do not alter database schema unless issue is from
  admin AND specifically requires it.
- Minimal fix only. Do not refactor adjacent code.
- Report any ambiguity before proceeding.`

    // Save prompt and update status to queued
    await supabase.from('issues').update({
      pipeline_prompt: prompt,
      status: 'queued',
      pipeline_started_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }).eq('id', issueId)

    // TODO: Send to Paperclip API when credentials are configured
    // const paperclipUrl = Deno.env.get('PAPERCLIP_API_URL')
    // const paperclipKey = Deno.env.get('PAPERCLIP_API_KEY')
    // const agentId = Deno.env.get('PAPERCLIP_AGENT_ID')
    // const projectId = Deno.env.get('PAPERCLIP_PROJECT_ID')
    //
    // if (paperclipUrl && paperclipKey) {
    //   const severityMap: Record<string, string> = {
    //     critical: 'urgent', high: 'high', normal: 'medium', low: 'low'
    //   }
    //   await fetch(paperclipUrl, {
    //     method: 'POST',
    //     headers: {
    //       'Content-Type': 'application/json',
    //       'Authorization': `Bearer ${paperclipKey}`,
    //     },
    //     body: JSON.stringify({
    //       agent_id: agentId,
    //       project_id: projectId,
    //       title: `AUTO-FIX [${issue.severity}]: ${issue.title}`,
    //       body: prompt,
    //       priority: severityMap[issue.severity] ?? 'medium',
    //     }),
    //   })
    // }

    return json({ ok: true, issue_id: issueId, status: 'queued' })
  } catch (err) {
    console.error('Issue pipeline error:', err)

    // Try to update the issue status on failure
    try {
      const supabase = createClient(
        Deno.env.get('SUPABASE_URL')!,
        Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
      )
      const payload = await req.clone().json().catch(() => ({}))
      const issueId = payload?.record?.id ?? payload?.id
      if (issueId) {
        await supabase.from('issues').update({
          status: 'failed_build',
          resolution_notes: `Pipeline delivery failed: ${(err as Error).message}`,
          updated_at: new Date().toISOString(),
        }).eq('id', issueId)
      }
    } catch { /* swallow */ }

    return json({ error: (err as Error).message }, 500)
  }
})
